name: Elixir CI

on:
  push:   # Run on any push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["26.2.3"] # Define the OTP version [required]
        elixir: ["1.17.1"] # Define the elixir version [required]

    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Set MIX_ENV
        run: echo "MIX_ENV=test" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd hw_4 && mix deps.get

      - name: Run tests
        run: cd hw_4 && mix test

      - name: Run dialyxir
        run: cd hw_4 && mix dialyzer

      - name: Run credo
        run: cd hw_4 && mix credo --strict